#
# Copyright (C) 2023, Inria
# GRAPHDECO research group, https://team.inria.fr/graphdeco
# All rights reserved.
#
# This software is free for non-commercial, research and evaluation use
# under the terms of the LICENSE.md file.
#
# For inquiries contact  george.drettakis@inria.fr
#

import os
import torch
import torch.nn.functional as F   # ← NEW: needed for silhouette BCE loss
import numpy as np                  # ← NEW: needed for depth pre-processing
from random import randint
from utils.loss_utils import l1_loss, ssim
from gaussian_renderer import render, network_gui
import sys
from scene import Scene, GaussianModel
from utils.general_utils import safe_state, get_expon_lr_func
import uuid
from tqdm import tqdm
from utils.image_utils import psnr
from argparse import ArgumentParser, Namespace
from arguments import ModelParams, PipelineParams, OptimizationParams

try:
    from torch.utils.tensorboard import SummaryWriter
    TENSORBOARD_FOUND = True
except ImportError:
    TENSORBOARD_FOUND = False

try:
    from fused_ssim import fused_ssim
    FUSED_SSIM_AVAILABLE = True
except:
    FUSED_SSIM_AVAILABLE = False

try:
    from diff_gaussian_rasterization import SparseGaussianAdam
    SPARSE_ADAM_AVAILABLE = True
except:
    SPARSE_ADAM_AVAILABLE = False


# ─────────────────────────────────────────────────────────────────────────────
# DECOUPLED SUPERVISION: Camera classification helper
#
# Identifies whether a camera was generated by Zero123++ or is a real photo.
# Uses the naming convention written by inject_poses.py:
#   Real photos  → anchor_{base}.jpg
#   Synth views  → synth_{base}_v{0-5}.jpg
#
# If rename.py ran (sequential naming 00001.jpg ...), this function returns
# False for everything. In that case, set the SYNTH_CAM_IDS set below by
# loading the pose_manifest.json written by inject_poses.py.
# ─────────────────────────────────────────────────────────────────────────────

# Optional: populate this from inject_poses.py's pose_manifest.json if
# sequential naming was used (see notebook cell below training call).
SYNTH_CAM_IDS: set = set()   # colmap image_ids of synthetic cameras

def is_synthetic_view(cam) -> bool:
    """Returns True if this camera was produced by Zero123++, not a real photo."""
    name = cam.image_name
    # Primary check: anchor_/synth_ prefix naming (preferred — skip rename.py)
    if name.startswith("synth_"):
        return True
    if name.startswith("anchor_"):
        return False
    # Fallback: sequential naming — use colmap_id membership in SYNTH_CAM_IDS
    return int(getattr(cam, "colmap_id", -1)) in SYNTH_CAM_IDS


# ─────────────────────────────────────────────────────────────────────────────


def training(dataset, opt, pipe, testing_iterations, saving_iterations, checkpoint_iterations, checkpoint, debug_from):
    if not SPARSE_ADAM_AVAILABLE and opt.optimizer_type == "sparse_adam":
        sys.exit(
            f"Trying to use sparse adam but it is not installed, please install the correct rasterizer using pip install [3dgs_accel].")

    first_iter = 0
    tb_writer = prepare_output_and_logger(dataset)
    gaussians = GaussianModel(dataset.sh_degree, opt.optimizer_type)
    scene = Scene(dataset, gaussians)
    gaussians.training_setup(opt)
    if checkpoint:
        (model_params, first_iter) = torch.load(checkpoint)
        gaussians.restore(model_params, opt)

    bg_color = [1, 1, 1] if dataset.white_background else [0, 0, 0]
    background = torch.tensor(bg_color, dtype=torch.float32, device="cuda")

    # ─────────────────────────────────────────────────────────────────────────
    # DECOUPLED SUPERVISION — Phase 1: Pre-compute Depth-Anything-V2 priors
    #
    # We run Depth-Anything-V2 on every SYNTHETIC training camera ONCE before
    # the training loop, and inject the results into:
    #   cam.invdepthmap    — inverse depth map tensor [H, W]
    #   cam.depth_mask     — valid-pixel mask tensor   [H, W]
    #   cam.depth_reliable — True (gates the existing depth loss at line ~140)
    #
    # Real cameras are deliberately left with depth_reliable=False so the
    # existing depth loss does NOT fire for them (real photos need no geometric
    # prior — their photometric loss already provides full supervision).
    #
    # After this block, the existing depth loss code (lines ~140-150) handles
    # the depth term for synthetic views automatically. No further changes to
    # the depth loss arithmetic are needed.
    # ─────────────────────────────────────────────────────────────────────────
    print("\n[Decoupled Supervision] Pre-computing Depth-Anything-V2 priors for synthetic cameras...")
    _depth_priors_loaded = False
    try:
        from transformers import AutoImageProcessor, AutoModelForDepthEstimation
        from PIL import Image as PILImage

        _d_processor = AutoImageProcessor.from_pretrained(
            "depth-anything/Depth-Anything-V2-Large-hf"
        )
        _d_model = AutoModelForDepthEstimation.from_pretrained(
            "depth-anything/Depth-Anything-V2-Large-hf",
            torch_dtype=torch.float16
        ).to("cuda").eval()

        _synth_count = 0
        with torch.no_grad():
            for cam in scene.getTrainCameras():
                if not is_synthetic_view(cam):
                    continue

                # Convert GT image tensor [3, H, W] float32 → PIL RGB
                gt_np  = (cam.original_image.permute(1, 2, 0).cpu().numpy() * 255).astype(np.uint8)
                pil_img = PILImage.fromarray(gt_np)

                inputs  = _d_processor(images=pil_img, return_tensors="pt")
                inputs  = {k: v.to("cuda", dtype=torch.float16) for k, v in inputs.items()}
                outputs = _d_model(**inputs)

                # outputs.predicted_depth: [1, H_enc, W_enc] (fp16 from model).
                # Resize to the camera's resolution — works on every transformers version
                # regardless of whether the processor is DPTImageProcessor or
                # DepthAnythingImageProcessor (post_process_depth_estimation only
                # exists on the newer class and crashes on older installs).
                raw = outputs.predicted_depth                        # [1, H_enc, W_enc]
                if raw.dim() == 2:
                    raw = raw.unsqueeze(0)                           # [1, H_enc, W_enc]
                pred = F.interpolate(
                    raw.unsqueeze(1).float(),                        # [1, 1, H_enc, W_enc]
                    size=(cam.image_height, cam.image_width),
                    mode='bilinear',
                    align_corners=False,
                ).squeeze()                                          # [H, W], larger = closer

                # Normalise to [0, 1] — relative (scale-invariant) depth prior.
                # The scale-shift alignment at loss time handles the metric difference
                # between this relative prior and the absolute rendered depth.
                d_min, d_max = pred.min(), pred.max()
                inv_depth = (pred - d_min) / (d_max - d_min + 1e-8)  # [H, W]

                # Inject into camera object
                cam.invdepthmap    = inv_depth.cpu()                    # [H, W] float32
                cam.depth_mask     = (inv_depth > 0.05).float().cpu()   # valid pixels
                cam.depth_reliable = True
                _synth_count += 1

        del _d_model, _d_processor
        torch.cuda.empty_cache()
        print(f"[Decoupled Supervision] ✓ Depth priors injected for {_synth_count} synthetic cameras.")
        _depth_priors_loaded = True

    except Exception as _depth_exc:
        print(f"[Decoupled Supervision] ⚠  Depth-Anything-V2 unavailable: {_depth_exc}")
        print("   Continuing with silhouette-only supervision for synthetic views.")
        print("   Install with:  pip install transformers>=4.38  huggingface-hub")
    # ─────────────────────────────────────────────────────────────────────────

    iter_start = torch.cuda.Event(enable_timing=True)
    iter_end   = torch.cuda.Event(enable_timing=True)

    use_sparse_adam  = opt.optimizer_type == "sparse_adam" and SPARSE_ADAM_AVAILABLE
    depth_l1_weight  = get_expon_lr_func(opt.depth_l1_weight_init, opt.depth_l1_weight_final, max_steps=opt.iterations)

    viewpoint_stack   = scene.getTrainCameras().copy()
    viewpoint_indices = list(range(len(viewpoint_stack)))
    ema_loss_for_log        = 0.0
    ema_Ll1depth_for_log    = 0.0

    progress_bar = tqdm(range(first_iter, opt.iterations), desc="Training progress")
    first_iter += 1
    for iteration in range(first_iter, opt.iterations + 1):
        if network_gui.conn == None:
            network_gui.try_connect()
        while network_gui.conn != None:
            try:
                net_image_bytes = None
                custom_cam, do_training, pipe.convert_SHs_python, pipe.compute_cov3D_python, keep_alive, scaling_modifer = network_gui.receive()
                if custom_cam != None:
                    net_image = render(custom_cam, gaussians, pipe, background, scaling_modifier=scaling_modifer,
                                       use_trained_exp=dataset.train_test_exp, separate_sh=SPARSE_ADAM_AVAILABLE)[
                        "render"]
                    net_image_bytes = memoryview((torch.clamp(net_image, min=0, max=1.0) * 255).byte().permute(1, 2,
                                                                                                               0).contiguous().cpu().numpy())
                network_gui.send(net_image_bytes, dataset.source_path)
                if do_training and ((iteration < int(opt.iterations)) or not keep_alive):
                    break
            except Exception as e:
                network_gui.conn = None

        iter_start.record()

        gaussians.update_learning_rate(iteration)

        # Every 1000 its we increase the levels of SH up to a maximum degree
        if iteration % 1000 == 0:
            gaussians.oneupSHdegree()

        # Pick a random Camera
        if not viewpoint_stack:
            viewpoint_stack   = scene.getTrainCameras().copy()
            viewpoint_indices = list(range(len(viewpoint_stack)))
        rand_idx     = randint(0, len(viewpoint_indices) - 1)
        viewpoint_cam = viewpoint_stack.pop(rand_idx)
        vind          = viewpoint_indices.pop(rand_idx)

        # Render
        if (iteration - 1) == debug_from:
            pipe.debug = True

        # ── DECOUPLED SUPERVISION: Force black background for synthetic views ──
        # The silhouette loss (below) compares rendered luminance against a
        # binary mask derived from the black-background GT image. If random
        # background is used for synthetic views, the luminance-based pseudo-alpha
        # becomes unreliable. Real views keep the original background logic.
        if is_synthetic_view(viewpoint_cam):
            bg = torch.zeros(3, device="cuda")          # black — required for silhouette
        else:
            bg = torch.rand((3), device="cuda") if opt.random_background else background

        render_pkg = render(viewpoint_cam, gaussians, pipe, bg, use_trained_exp=dataset.train_test_exp,
                            separate_sh=SPARSE_ADAM_AVAILABLE)
        image, viewspace_point_tensor, visibility_filter, radii = (
            render_pkg["render"],
            render_pkg["viewspace_points"],
            render_pkg["visibility_filter"],
            render_pkg["radii"],
        )

        if viewpoint_cam.alpha_mask is not None:
            alpha_mask = viewpoint_cam.alpha_mask.cuda()
            image *= alpha_mask

        # ─────────────────────────────────────────────────────────────────────
        # DECOUPLED SUPERVISION — Phase 2: Source-aware loss
        #
        # Real photos   → full photometric loss (L1 + SSIM) + optional depth
        #                 Supervises: xyz, opacity, scale, rotation, SH colour
        #
        # Synthetic views → geometry-only loss (silhouette + depth)
        #                   Supervises: xyz, opacity, scale, rotation
        #                   Does NOT supervise SH colour coefficients.
        #                   This prevents Zero123++'s hallucinated textures from
        #                   creating gradient conflicts that collapse opacity.
        # ─────────────────────────────────────────────────────────────────────
        gt_image = viewpoint_cam.original_image.cuda()

        if not is_synthetic_view(viewpoint_cam):
            # ── REAL PHOTO: Full photometric supervision (unchanged) ──────────
            Ll1 = l1_loss(image, gt_image)
            if FUSED_SSIM_AVAILABLE:
                ssim_value = fused_ssim(image.unsqueeze(0), gt_image.unsqueeze(0))
            else:
                ssim_value = ssim(image, gt_image)
            loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim_value)

            # Depth regularization for real cameras (unchanged — fires only if
            # invdepthmap was provided, which it is NOT for real cameras by design)
            Ll1depth_pure = 0.0
            if depth_l1_weight(iteration) > 0 and viewpoint_cam.depth_reliable:
                invDepth      = render_pkg["depth"]
                mono_invdepth = viewpoint_cam.invdepthmap.cuda()
                depth_mask    = viewpoint_cam.depth_mask.cuda()
                Ll1depth_pure = torch.abs((invDepth - mono_invdepth) * depth_mask).mean()
                Ll1depth      = depth_l1_weight(iteration) * Ll1depth_pure
                loss         += Ll1depth
                Ll1depth      = Ll1depth.item()
            else:
                Ll1depth = 0

        else:
            # ── SYNTHETIC VIEW (Zero123++): Geometry-only supervision ─────────

            # (A) Silhouette loss ─────────────────────────────────────────────
            # Zero123++ outputs have a black background (our process_for_zero123()
            # pastes onto a black canvas). Any pixel with luminance > 0.05 is
            # object; anything below is background.
            #
            # We compare the rendered luminance (which acts as pseudo-alpha on a
            # black background) against this binary mask. This pushes Gaussian
            # opacity to match the known object extent without touching SH colour.
            with torch.no_grad():
                gt_lum  = 0.299 * gt_image[0] + 0.587 * gt_image[1] + 0.114 * gt_image[2]  # [H,W]
                # Threshold at 0.30: safely above Zero123++ grey backgrounds (~0.5
                # luminance) while keeping dimly-lit object pixels. If your synth
                # views have pure black backgrounds (remove_bg.py was run), drop
                # this back to 0.05.
                gt_mask = (gt_lum > 0.30).float()                                             # [H,W]

            rendered_alpha = (0.299 * image[0] + 0.587 * image[1] + 0.114 * image[2])        # [H,W]
            sil_loss = F.binary_cross_entropy(
                rendered_alpha.clamp(1e-6, 1.0 - 1e-6), gt_mask
            )

            loss     = 0.5 * sil_loss          # initialise; depth term added below
            Ll1      = sil_loss                 # used in the logging/reporting calls
            Ll1depth = 0

            # (B) Depth loss ──────────────────────────────────────────────────
            # Fires for synthetic cameras where Depth-Anything-V2 priors were
            # injected (depth_reliable=True). The existing depth_l1_weight
            # scheduler decays this term over training — correct behaviour.
            #
            # Scale-shift invariant alignment: necessary because Depth-Anything-V2
            # outputs RELATIVE depth (no metric scale) while render_pkg["depth"]
            # is in absolute scene units. We fit a linear s*d_prior + t → d_render
            # on the valid pixel subset before computing the L1.
            Ll1depth_pure = 0.0
            if depth_l1_weight(iteration) > 0 and viewpoint_cam.depth_reliable:
                invDepth      = render_pkg["depth"]                # [1,H,W] or [H,W]
                mono_invdepth = viewpoint_cam.invdepthmap.cuda()   # [H,W]
                depth_mask_t  = viewpoint_cam.depth_mask.cuda()    # [H,W]

                # Flatten for least-squares alignment
                d_r = invDepth.reshape(-1)
                d_p = mono_invdepth.reshape(-1)
                m   = depth_mask_t.reshape(-1).bool()

                if m.sum() > 50:
                    # Closed-form ordinary least squares: min ||s*d_p + t - d_r||
                    d_p_m = d_p[m]
                    d_r_m = d_r[m]
                    mu_p  = d_p_m.mean()
                    mu_r  = d_r_m.mean()
                    var_p = ((d_p_m - mu_p) ** 2).mean().clamp(min=1e-8)
                    cov   = ((d_p_m - mu_p) * (d_r_m - mu_r)).mean()
                    scale = cov / var_p
                    shift = mu_r - scale * mu_p
                    d_p_aligned = (scale * d_p + shift).clamp(min=0.0)
                    Ll1depth_pure = (torch.abs(d_r - d_p_aligned) * depth_mask_t.reshape(-1)).mean()
                else:
                    # Fallback if too few valid pixels (very sparse scene)
                    Ll1depth_pure = torch.abs((invDepth - mono_invdepth) * depth_mask_t).mean()

                Ll1depth_weighted = depth_l1_weight(iteration) * Ll1depth_pure
                loss     = loss + Ll1depth_weighted
                Ll1depth = Ll1depth_weighted.item()

        # ── Gaussian count guard ──────────────────────────────────────────────
        # If almost all Gaussians have been pruned, the rasterizer backward pass
        # will crash with a tensor shape mismatch ([0,0,3] vs [0,16,3]).
        # We skip the backward and let densification recover on the next step.
        if gaussians.get_xyz.shape[0] < 10:
            print(f"\n[WARN] Only {gaussians.get_xyz.shape[0]} Gaussians remain at "
                  f"iteration {iteration}. Skipping backward pass.")
            iter_end.record()
            with torch.no_grad():
                ema_loss_for_log     = 0.4 * loss.item() + 0.6 * ema_loss_for_log
                ema_Ll1depth_for_log = 0.4 * Ll1depth    + 0.6 * ema_Ll1depth_for_log
                if iteration % 10 == 0:
                    progress_bar.set_postfix({
                        "Loss": f"{ema_loss_for_log:.{7}f}",
                        "Depth Loss": f"{ema_Ll1depth_for_log:.{7}f}"
                    })
                    progress_bar.update(10)
                if iteration == opt.iterations:
                    progress_bar.close()
            continue

        loss.backward()

        iter_end.record()

        with torch.no_grad():
            # Progress bar
            ema_loss_for_log     = 0.4 * loss.item() + 0.6 * ema_loss_for_log
            ema_Ll1depth_for_log = 0.4 * Ll1depth    + 0.6 * ema_Ll1depth_for_log

            if iteration % 10 == 0:
                progress_bar.set_postfix(
                    {"Loss": f"{ema_loss_for_log:.{7}f}", "Depth Loss": f"{ema_Ll1depth_for_log:.{7}f}"})
                progress_bar.update(10)
            if iteration == opt.iterations:
                progress_bar.close()

            # Log and save
            training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end),
                            testing_iterations, scene, render,
                            (pipe, background, 1., SPARSE_ADAM_AVAILABLE, None, dataset.train_test_exp),
                            dataset.train_test_exp)
            if (iteration in saving_iterations):
                print("\n[ITER {}] Saving Gaussians".format(iteration))
                scene.save(iteration)

            # Densification
            if iteration < opt.densify_until_iter:
                # Keep track of max radii in image-space for pruning
                gaussians.max_radii2D[visibility_filter] = torch.max(gaussians.max_radii2D[visibility_filter],
                                                                     radii[visibility_filter])
                gaussians.add_densification_stats(viewspace_point_tensor, visibility_filter)

                if iteration > opt.densify_from_iter and iteration % opt.densification_interval == 0:
                    size_threshold = 20 if iteration > opt.opacity_reset_interval else None
                    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold,
                                                radii)

                if iteration % opt.opacity_reset_interval == 0 or (
                        dataset.white_background and iteration == opt.densify_from_iter):
                    gaussians.reset_opacity()

            # Optimizer step
            if iteration < opt.iterations:
                gaussians.exposure_optimizer.step()
                gaussians.exposure_optimizer.zero_grad(set_to_none=True)
                if use_sparse_adam:
                    visible = radii > 0
                    gaussians.optimizer.step(visible, radii.shape[0])
                    gaussians.optimizer.zero_grad(set_to_none=True)
                else:
                    gaussians.optimizer.step()
                    gaussians.optimizer.zero_grad(set_to_none=True)

            if (iteration in checkpoint_iterations):
                print("\n[ITER {}] Saving Checkpoint".format(iteration))
                torch.save((gaussians.capture(), iteration), scene.model_path + "/chkpnt" + str(iteration) + ".pth")


def prepare_output_and_logger(args):
    if not args.model_path:
        if os.getenv('OAR_JOB_ID'):
            unique_str = os.getenv('OAR_JOB_ID')
        else:
            unique_str = str(uuid.uuid4())
        args.model_path = os.path.join("./output/", unique_str[0:10])

    # Set up output folder
    print("Output folder: {}".format(args.model_path))
    os.makedirs(args.model_path, exist_ok=True)
    with open(os.path.join(args.model_path, "cfg_args"), 'w') as cfg_log_f:
        cfg_log_f.write(str(Namespace(**vars(args))))

    # Create Tensorboard writer
    tb_writer = None
    if TENSORBOARD_FOUND:
        tb_writer = SummaryWriter(args.model_path)
    else:
        print("Tensorboard not available: not logging progress")
    return tb_writer


def training_report(tb_writer, iteration, Ll1, loss, l1_loss, elapsed, testing_iterations, scene: Scene, renderFunc,
                    renderArgs, train_test_exp):
    if tb_writer:
        tb_writer.add_scalar('train_loss_patches/l1_loss', Ll1.item(), iteration)
        tb_writer.add_scalar('train_loss_patches/total_loss', loss.item(), iteration)
        tb_writer.add_scalar('iter_time', elapsed, iteration)

    # Report test and samples of training set
    if iteration in testing_iterations:
        torch.cuda.empty_cache()
        validation_configs = ({'name': 'test', 'cameras': scene.getTestCameras()},
                              {'name': 'train',
                               'cameras': [scene.getTrainCameras()[idx % len(scene.getTrainCameras())] for idx in
                                           range(5, 30, 5)]})

        for config in validation_configs:
            if config['cameras'] and len(config['cameras']) > 0:
                l1_test  = 0.0
                psnr_test = 0.0
                for idx, viewpoint in enumerate(config['cameras']):
                    image    = torch.clamp(renderFunc(viewpoint, scene.gaussians, *renderArgs)["render"], 0.0, 1.0)
                    gt_image = torch.clamp(viewpoint.original_image.to("cuda"), 0.0, 1.0)
                    if train_test_exp:
                        image    = image[...,    image.shape[-1] // 2:]
                        gt_image = gt_image[..., gt_image.shape[-1] // 2:]
                    if tb_writer and (idx < 5):
                        tb_writer.add_images(config['name'] + "_view_{}/render".format(viewpoint.image_name),
                                             image[None], global_step=iteration)
                        if iteration == testing_iterations[0]:
                            tb_writer.add_images(config['name'] + "_view_{}/ground_truth".format(viewpoint.image_name),
                                                 gt_image[None], global_step=iteration)
                    l1_test  += l1_loss(image, gt_image).mean().double()
                    psnr_test += psnr(image, gt_image).mean().double()
                psnr_test /= len(config['cameras'])
                l1_test   /= len(config['cameras'])
                print("\n[ITER {}] Evaluating {}: L1 {} PSNR {}".format(iteration, config['name'], l1_test, psnr_test))
                if tb_writer:
                    tb_writer.add_scalar(config['name'] + '/loss_viewpoint - l1_loss', l1_test, iteration)
                    tb_writer.add_scalar(config['name'] + '/loss_viewpoint - psnr', psnr_test, iteration)

        if tb_writer:
            tb_writer.add_histogram("scene/opacity_histogram", scene.gaussians.get_opacity, iteration)
            tb_writer.add_scalar('total_points', scene.gaussians.get_xyz.shape[0], iteration)
        torch.cuda.empty_cache()


if __name__ == "__main__":
    # Set up command line argument parser
    parser = ArgumentParser(description="Training script parameters")
    lp = ModelParams(parser)
    op = OptimizationParams(parser)
    pp = PipelineParams(parser)
    parser.add_argument('--ip', type=str, default="127.0.0.1")
    parser.add_argument('--port', type=int, default=6009)
    parser.add_argument('--debug_from', type=int, default=-1)
    parser.add_argument('--detect_anomaly', action='store_true', default=False)
    parser.add_argument("--test_iterations", nargs="+", type=int, default=[7_000, 30_000])
    parser.add_argument("--save_iterations", nargs="+", type=int, default=[7_000, 30_000])
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument('--disable_viewer', action='store_true', default=False)
    parser.add_argument("--checkpoint_iterations", nargs="+", type=int, default=[])
    parser.add_argument("--start_checkpoint", type=str, default=None)
    args = parser.parse_args(sys.argv[1:])
    args.save_iterations.append(args.iterations)

    print("Optimizing " + args.model_path)

    # Initialize system state (RNG)
    safe_state(args.quiet)

    # Start GUI server, configure and run training
    if not args.disable_viewer:
        network_gui.init(args.ip, args.port)
    torch.autograd.set_detect_anomaly(args.detect_anomaly)
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations,
             args.checkpoint_iterations, args.start_checkpoint, args.debug_from)

    # All done
    print("\nTraining complete.")
